Feature/fds navigation mobile version
fintraffic-design/fds-coreui-components pull request #40
Opened 2023-09-15 07:46 UTC by Joonas-M-S

Elikkäs pyrin olemaan rikkomatta mitään. Nyt tuo navigaatio menee navigaationapin taakse, kun ruudun koko on tarpeeksi pieni. Lisäsin myös tuommoisen `mobileOrder` propertyn, jonka avulla navigaation itemejä voi järjestellä haluamaansa järjestykseen mobiilinäkymässä. Tämä sen takia, että näyttäisi Fintrafficin projekteissa olevan sellainen tapa, että hakukenttä on sijoitettu navigaation oikeaan nurkkaan desktopilla, mutta mobiililla se on listan ensimmäisenä.

2023-11-24 08:44 UTC, Joonas-M-S commented
Hi, sorry for not getting back to this earlier. So there are two changes that need to be made
- `mobile` -> `verticalMenuThreshold`
- change media query to container one
I'll try to make those changes today

2023-11-27 09:09 UTC, Haprog commented
The filenames and structure changed a bit in main since #59 was merged. I can help merge the changes into this branch.

2023-12-04 13:58 UTC, Haprog requested changes
Found couple of minor things but otherwise looks good to me.

2023-12-08 11:22 UTC, Haprog approved these changes

2023-12-08 11:30 UTC, Haprog commented
@ninopenttinen if this looks ok to you know, let's squash and merge this.

2023-12-08 13:03 UTC, ninopenttinen approved these changes
👌

2023-12-08 13:51 UTC, merged